name: Go Test and Coverage

on:
  push:
    branches:
      - master # Adjust to the default branch of your repository

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1 # Adjust to your Go version

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

  coverage:
    name: Generate Code Coverage Report
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1 # Adjust to your Go version

      - name: Install Codecov
        run: |
          curl -s https://codecov.io/bash > codecov
          chmod +x codecov
          sudo mv codecov /usr/local/bin/codecov

      - name: Run Code Coverage
        run: go test -v ./... -coverprofile=coverage.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
